export const ALLOWED_ROLES = new Set([
  "super_admin",
  "admin",
  "moderator",
  "supervisor",
  "finance",
  "call_center",
  "provider",
  "representative",
  "employer",
  "user",
]);

export const CMS_TABLES = {
  cms_categories: {
    orderBy: "sort_order",
    jsonColumns: new Set(),
    booleanColumns: new Set(["is_active"]),
    columns: [
      "id",
      "name",
      "name_en",
      "icon_url",
      "color_gradient",
      "color_overlay",
      "color_chip_bg",
      "color_chip_text",
      "color_accent",
      "sort_order",
      "is_active",
    ],
  },
  cms_services: {
    orderBy: "sort_order",
    jsonColumns: new Set(["features", "available_cities"]),
    booleanColumns: new Set(["is_active"]),
    columns: [
      "id",
      "slug",
      "title",
      "title_en",
      "image_url",
      "description",
      "rating",
      "total_reviews",
      "total_orders",
      "features",
      "available_cities",
      "category_id",
      "commission_percent",
      "is_active",
      "sort_order",
    ],
  },
  cms_service_packages: {
    orderBy: "sort_order",
    jsonColumns: new Set(["features"]),
    booleanColumns: new Set(),
    columns: [
      "id",
      "service_id",
      "name",
      "price",
      "original_price",
      "features",
      "sort_order",
    ],
  },
  cms_special_offers: {
    orderBy: "sort_order",
    jsonColumns: new Set(),
    booleanColumns: new Set(["is_active"]),
    columns: [
      "id",
      "title_bn",
      "title_en",
      "discount_bn",
      "discount_en",
      "description_bn",
      "description_en",
      "service_slug",
      "badge",
      "gradient",
      "border_color",
      "accent_color",
      "bg_accent",
      "is_active",
      "expires_at",
      "sort_order",
    ],
  },
  cms_hero_banners: {
    orderBy: "sort_order",
    jsonColumns: new Set(),
    booleanColumns: new Set(["is_active"]),
    columns: [
      "id",
      "title_bn",
      "title_en",
      "subtitle_bn",
      "subtitle_en",
      "image_url",
      "is_active",
      "sort_order",
    ],
  },
  cms_homepage_sections: {
    orderBy: "sort_order",
    jsonColumns: new Set(["service_slugs"]),
    booleanColumns: new Set(["is_active"]),
    columns: [
      "id",
      "section_key",
      "title_bn",
      "title_en",
      "service_slugs",
      "sort_order",
      "is_active",
    ],
  },
};

export const passwordPolicyMessage =
  "Password must be at least 8 characters and include uppercase, lowercase, a number, and a special character.";